#!/usr/bin/python -u
import os, json, pystache

carbon_config = {}

carbon_config_json = json.loads(os.getenv('CARBON_CONFIG', '{}'))

with open ("/opt/graphite/conf/carbon.conf.mustache", "r") as carbon_config_template:
  with open ("/opt/graphite/conf/carbon.conf", "w") as carbon_config_out:
    data = carbon_config_template.read()
    carbon_config_out.write(pystache.render(data, carbon_config))

with open ("/opt/graphite/webapp/graphite/local_settings.py.mustache", "r") as local_settings_template:
  with open ("/opt/graphite/webapp/graphite/local_settings.py", "w") as local_settings_out:
    data = local_settings_template.read()
    local_settings_out.write(pystache.render(data, carbon_config))

execfile('/sbin/my_init')
